// Copyright Y56380X https://github.com/Y56380X/RESTly.
// Licensed under the MIT License.

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Restly;

[Generator]
public class FoundationSourceGenerator : IIncrementalGenerator
{
	private const string ClientAttributeCode =
		"""
		// <auto-generated/>
		namespace Restly
		{
		    [System.AttributeUsage(System.AttributeTargets.Assembly)]
		    public class RestlyClientAttribute : System.Attribute
		    {
		        public RestlyClientAttribute(string clientDefinition, string clientName) { }
		    }
		}
		""";
	
	private const string ResponseClassesCode =
		"""
		// <auto-generated/>
		namespace Restly
		{
			public record Response(bool IsSuccessStatusCode, HttpStatusCode StatusCode);
		
			public record Response<T>(bool IsSuccessStatusCode, HttpStatusCode StatusCode, T? Model)
			        : Response(IsSuccessStatusCode, StatusCode);
		}
		""";
	
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
			"RestlyClientAttribute.g.cs",
			SourceText.From(ClientAttributeCode, Encoding.UTF8)));
		
		context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
			"RestlyResponse.g.cs",
			SourceText.From(ResponseClassesCode, Encoding.UTF8)));
	}
}